# Используем Node.js образ для React-приложения
FROM node:14

# Устанавливаем рабочую директорию
WORKDIR /frontend

# Копируем package.json и устанавливаем зависимости
COPY package.json /frontend/
RUN npm install

# Копируем весь проект в контейнер
COPY . /frontend/

# Команда для запуска React сервера
CMD ["npm", "start"]
