# Generated by Django 5.1.1 on 2024-09-25 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('nationality', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('secondary', 'Среднее'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Докторская степень')], max_length=20, verbose_name='Уровень образования')),
                ('institution', models.CharField(max_length=100, verbose_name='Учебное заведение')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hr_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('single', 'Не женат/не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведён/Разведена'), ('widowed', 'Вдова/Вдовец')], max_length=10, verbose_name='Семейное положение')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='Количество детей')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='hr_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Семья',
                'verbose_name_plural': 'Семья',
            },
        ),
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен состоять из двух заглавных букв и 7 цифр.', regex='^[A-Z]{2}\\d{7}$')], verbose_name='Номер паспорта')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Кем выдан')),
                ('date_issued', models.DateField(verbose_name='Дата выдачи')),
                ('date_expiry', models.DateField(verbose_name='Срок действия')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_info', to='hr_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Паспортная информация',
                'verbose_name_plural': 'Паспортная информация',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100, verbose_name='Работодатель')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='hr_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateField(verbose_name='Дата получения')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.certification', verbose_name='Сертификат')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr_app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сертификат сотрудника',
                'verbose_name_plural': 'Сертификаты сотрудников',
                'unique_together': {('employee', 'certification')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('native', 'Родной')], max_length=12, verbose_name='Уровень владения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='hr_app.employee', verbose_name='Сотрудник')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык сотрудника',
                'verbose_name_plural': 'Языки сотрудников',
                'unique_together': {('employee', 'language')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr_app.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
